server:
  port: 8080

spring:
  application:
    name: jpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teamdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update #???(create/update/none)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  public-data:
    url: "엔드포인트"
    service-key: "본인 키(특수문자 섞여있을경우에 디코딩된 키로 넣어주세요!"